https://sandbox.bankmandiri.co.id/openapi/transactions/v2.0/bank-statement

{
"accountNo":"1150097011284",
"fromDateTime":"2022-05-18T00:00:00+07:00",
"toDateTime":"2022-05-19T14:00:00+07:00",
"additionalInfo":
{
"pageNumber":"1"
}
}

Header Parameters
Authorization
Bearer < token >
String
Required
Content-Type
application/json
String
Required
X-TIMESTAMP
FORMAT: yyyy-MM-ddTHH:mm:ssTZD
String
Required
X-SIGNATURE
Transaction signature. Please refer to Transaction Signature section
String
Required
X-PARTNER-ID
Partner ID given by Mandiri upon onboarding process
String(16)
Required
X-EXTERNAL-ID
Numeric String. Unique ID per request generated by partner
String(19)
Required
CHANNEL-ID
Channel ID from partner
Number(5)
Required
Body Parameters
accountNo
Numeric String. Registered partner account number
String(13)
Required
fromDateTime
FORMAT: yyyy-MM-ddTHH:mm:ssTZD. From DateTime to get descending order record
String(25)
Required
toDateTime
FORMAT: yyyy-MM-ddTHH:mm:ssTZD. End DateTime to to get descending order record
String(25)
Required
pageNumber
Page number to be retrieved
String(5)
Required
