https://sandbox.bankmandiri.co.id/openapi/transactions/v2.0/transfer-va/inquiry-intrabank

{
"customerNo":"60004398552",
"partnerServiceId":"89508",
"virtualAccountNo":"124005900176133",
"amount":
{
"value":"20000.00",
"currency":"IDR"
},
"language":"id",
"sourceAccountNo":"1150007482849",
"sourceAccountType":"S",
"additionalInfo":
{
"additionalBillKey":""
}
}

Header Parameters
Authorization
Bearer < token >
String
Required
Content-Type
application/json
String
Required
X-TIMESTAMP
FORMAT: yyyy-MM-ddTHH:mm:ssTZD
String
Required
X-SIGNATURE
Transaction signature. Please refer to Transaction Signature section
String
Required
X-PARTNER-ID
Partner ID given by Mandiri upon onboarding process
String(16)
Required
X-EXTERNAL-ID
Numeric String. Unique ID per request generated by partner
String(19)
Required
CHANNEL-ID
Channel ID from partner
Number(5)
Required
Body Parameters
partnerServiceId
Company/Biller Code. Sample: 50012
String(5)
Required
customerNo
Numeric string. Registered partner account number.
String (13)
Required
virtualAccountNo
Billing ID / virtual Account No
String(20)
Required
sourceAccountNo
Source Account No of the registered account
String(1)
Required
sourceAccountType
Account type of the registered account. D : Giro, S : Saving
String(1)
Required
value
Billing amount value
String(16)
Required
currency
Billing currency code. Sample: IDR, USD
String(3)
Optional