https://sandbox.bankmandiri.co.id/openapi/customers/v2.0/account-inquiry-external

{
"beneficiaryBankCode":"014",
"beneficiaryAccountNo":"60004400184",
"additionalInfo":
{
"switcher":""
}
}

PARAMETERS
Header Parameters
Authorization
Bearer < token >
String
Required
Content-Type
application/json
String
Required
X-TIMESTAMP
FORMAT: yyyy-MM-ddTHH:mm:ssTZD
String
Required
X-SIGNATURE
Transaction signature. Please refer to Transaction Signature section
String
Required
X-PARTNER-ID
Partner ID given by Mandiri upon onboarding process
String(16)
Required
X-EXTERNAL-ID
Numeric String. Unique ID per request generated by partner
String(19)
Required
CHANNEL-ID
Channel ID from partner
Number(5)
Required
Body Parameters
beneficiaryAccountNo
Numeric string. Other bank destination account number
String(19)
Required
beneficiaryBankCode
Account Issuing Bank Code (11 digit SWIFT Bank Code or 3 Digit Bank Code)
String(11)
Required
switcher
PRIMA (Default) or ATMB
String(7)
Optional