https://sandbox.bankmandiri.co.id/openapi/transaction/v1.0/transfer-va/report

{
"partnerServiceId": "89661",
"startDate": "2022-12-16",
"startTime": "14:09:11+07:00",
"endDate": "2022-12-16",
"endTime": "23:56:11+07:00",
"additionalInfo": {}
}

Header Parameters
Authorization
Bearer < token >
String
Required
Content-Type
application/json
String
Required
X-TIMESTAMP
FORMAT: yyyy-MM-ddTHH:mm:ssTZD
String
Required
X-SIGNATURE
Transaction signature. Please refer to Transaction Signature section
String
Required
X-PARTNER-ID
Partner ID given by Mandiri upon onboarding process
String(16)
Required
X-EXTERNAL-ID
Numeric String. Unique ID per request generated by partner
String(19)
Required
Body Parameters
partnerServiceId
3 space padding left + 5 digit company code
String(8)
Required
startDate
Start date of get report period. FORMAT: 'yyyy-MM-dd'
String(10)
Required
startTime
Start time of get report period. FORMAT: 'HH:mm:ssTZD'
String(14)
Required
endDate
End date of get report period. FORMAT: 'yyyy-MM-dd'
String(10)
Required
endTime
End time of get report period. FORMAT: 'HH:mm:ssTZD'
String(14)
Optional
