https://sandbox.bankmandiri.co.id/openapi/transactions/v2.0/transfer-intrabank

{
"partnerReferenceNo":"ITN0001",
"amount":
{
"value":"11000.00",
"currency":"IDR"
},
"sourceAccountNo":"1150006399259",
"beneficiaryAccountNo":"60004400184",
"remark":"PTROpenAPI",
"transactionDate":"2022-06-20T10:31:22+07:00",
"beneficiaryEmail":"sandbox_test@gmail.com",
"additionalInfo":
{
"reportCode":"abcd",
"senderInstrument":"1",
"senderAccountNo":"08786561231224",
"senderName":"rendimatrido",
"senderCountry":"id",
"senderCostumerType":"1",
"beneficiaryAccountName":"AjojiAjojo",
"beneficiaryInstrument":"1",
"beneficiaryCustomerType":"1"
}
}

PARAMETERS
Header Parameters
Authorization
Bearer < token >
String
Required
Content-Type
application/json
String
Required
X-TIMESTAMP
FORMAT: yyyy-MM-ddTHH:mm:ssTZD
String
Required
X-SIGNATURE
Transaction signature. Please refer to Transaction Signature section
String
Required
X-PARTNER-ID
Partner ID given by Mandiri upon onboarding process
String(16)
Required
X-EXTERNAL-ID
Numeric String. Unique ID per request generated by partner
String(19)
Required
CHANNEL-ID
Channel ID from partner
Number(5)
Required
Body Parameters
sourceAccountNo
Numeric string. registered partner account number
String(13)
Required
beneficiaryAccountNo
Numeric string. Mandiri destination account number
String(13)
Required
value
Applicable minimum transfer value of IDR 10000.00 and equivalent to other currencies per transaction
Decimal (19,2)
Required
currency
Credit Currency
String(3)
Required
transactionDate
Today Date FORMAT: yyyy-MM-ddTHH:mm:ssTZD
String (10)
Required
partnerReferenceNo
Unique transaction ID generated by partner. This value will be needed for transfer status inquiry along with X-EXTERNAL-ID
String(19)
Required
remark
Transaction remark. This value will also be used for settlement parameter on MT940 report
String(40)
Optional
beneficiaryEmail
Email address for sending email notifications to the beneficiary account owner
String(100)
Optional