https://sandbox.bankmandiri.co.id/openapi/transactions/v2.0/transfer-rtgs

{
"partnerReferenceNo":"RT002",
"sourceAccountNo":"1150097011284",
"beneficiaryAccountNo":"1390094033549",
"amount":
{
"value":"100075000.00",
"currency":"IDR"
},
"transactionDate":"2022-05-19T17:32:57+07:00",
"feeType":"BEN",
"remark":"756183471124124",
"beneficiaryEmail":"sandbox_test@gmail.com",
"beneficiaryBankCode":"CENAIDJA",
"beneficiaryAccountName":"TESTSNAPRTGS",
"beneficiaryBankName":"BANKCENTRALASIA",
"beneficiaryAddress":"Jakarta",
"beneficiaryCustomerResidence":"1",
"beneficiaryCustomerType":"1",
"senderCustomerResidence":"1",
"senderCustomerType":"1",
"additionalInfo":
{
"reportCode":"",
"senderInstrument":"",
"senderAccountNo":"",
"senderCountry":"",
"senderName":"",
"beneficiaryInstrument":"",
"beneficiaryCustomerType":""
}
}

PARAMETERS
Header Parameters
Authorization
Bearer < token >
String
Required
Content-Type
application/json
String
Required
X-TIMESTAMP
FORMAT: yyyy-MM-ddTHH:mm:ssTZD
String
Required
X-SIGNATURE
Transaction signature. Please refer to Transaction Signature section
String
Required
X-PARTNER-ID
Partner ID given by Mandiri upon onboarding process
String(16)
Required
X-EXTERNAL-ID
Numeric String. Unique ID per request generated by partner
String(19)
Required
CHANNEL-ID
Channel ID from partner
Number(5)
Required
Body Parameters
sourceAccountNo
Numeric string. registered partner account number
String(13)
Required
beneficiaryAccountNo
Numeric string. other bank destination account number
String(19)
Required
value
Applicable minimum transfer value of IDR 100 Million
Decimal (19,2)
Required
currency
Must be filled with IDR only
String(3)
Required
transactionDate
Current Date in yyyy-MM-ddTHH:mm:ssTZD
String(10)
Required
partnerReferenceNo
Unique transaction ID generated by partner. This value will be needed for transfer status inquiry along with X-EXTERNAL-ID
String (19)
Required
remark
Transaction remark. This value will also be used for settlement parameter on MT940 report
String (40)
Optional
beneficiaryBankCode
Account Issuing Bank Code (11 digit SWIFT Bank Code or 3 Digit Bank Code)
String(11)
Required
beneficiaryBankName
Other bank destination bank Name
String(60)
Required
beneficiaryAccountName
Other bank destination account name
String(70)
Required
beneficiaryEmail
Email address for sending email notifications to the beneficiary account owner
String (100)
Optional
beneficiaryCustomerResidence
'1' for Indonesian Citizen, '2' for Non Indonesian Citizen
String (1)
Optional
beneficiaryCustomerType
'1' for perorangan (individual), '2' for korporasi (corporate), '3' for Pemerintahan (government)
String (1)
Optional
senderCustomerResidence
'1' for Indonesian Citizen, '2' for Non Indonesian Citizen
String (1)
Optional
senderCustomerType
'1' for perorangan (individual), '2' for korporasi (corporate), '3' for Pemerintahan (government)
String(1)
Optional

