https://sandbox.bankmandiri.co.id/openapi/transactions/v2.0/transfer/status

{
"originalExternalId":"504001",
"originalPartnerReferenceNo":"20220519214808964",
"serviceCode":"18"
}

Header Parameters
Authorization
Bearer < token >
String
Required
Content-Type
application/json
String
Required
X-TIMESTAMP
FORMAT: yyyy-MM-ddTHH:mm:ssTZD
String
Required
X-SIGNATURE
Transaction signature. Please refer to Transaction Signature section
String
Required
X-PARTNER-ID
Partner ID given by Mandiri upon onboarding process
String(16)
Required
X-EXTERNAL-ID
Numeric String. Unique ID per request generated by partner
String(19)
Required
CHANNEL-ID
Channel ID from partner
Number(5)
Required
Body Parameters
originalExternalID
Numeric String. Original External ID from the transaction to query
String (19)
Required
originalpartnerReferenceNo
Original Customer Reference Number from the transaction to query
String (19)
Required
serviceCode
Original Service Code from the transaction Response Code
String (2)
Required