https://sandbox.bankmandiri.co.id/openapi/transaction/v1.0/transfer-va/update-va

{
"partnerServiceId": "89661",
"customerNo": "8966112900000392",
"virtualAccountNo": "8966112900000392",
"virtualAccountName": "JokulDoe",
"virtualAccountEmail": "jokul@email.com",
"virtualAccountPhone": "6281214739522",
"trxId": "abcd12347",
"totalAmount": {
"value": "75000.00",
"currency": "IDR"
},
"billDetails": [
{
"billAmount": {
"value": "75000.00",
"currency": "IDR"
}
}
],
"expiredDate": "2022-14-12T23:59:59+07:00"
}

Header Parameters
Authorization
Bearer < token >
String
Required
Content-Type
application/json
String
Required
X-TIMESTAMP
FORMAT: yyyy-MM-ddTHH:mm:ssTZD
String
Required
X-SIGNATURE
Transaction signature. Please refer to Transaction Signature section
String
Required
X-PARTNER-ID
Partner ID given by Mandiri upon onboarding process
String(16)
Required
X-EXTERNAL-ID
Numeric String. Unique ID per request generated by partner
String(19)
Required
Body Parameters
partnerServiceId
3 space padding left + 5 digit company code
String(8)
Required
customerNo
partnerServiceId+customerNo
String (20)
Required
virtualAccountNo
3 space padding left + 5 digit company code + VirtualAccountNo
String(28)
Required
virtualAccountName
Customer name
String(255)
Required
virtualAccountEmail
Customer email
String(50)
Optional
virtualAccountPhone
Customer phone's number (Format : 62xxxxxxxxxxx)
String(20)
Optional
trxId
Transaction ID in partner system, must be unique
String(50)
Required
totalAmount
For close payment type, amount is filled by merchant. Can fill with '0.00' for open payment type
Object
Required
value
Minimum value is 10000.00. Sample : 75000.00
String(16,2)
Required
currency
Must be 'IDR'
String(3)
Required
billDetails
For close payment type, amount is filled by merchant. Can fill with '0.00' for open payment type
Array of Object
Required
billAmount
Object
Required
value
Minimum value is 10000.00. Sample : 75000.00
String(16,2)
Required
currency
Must be 'IDR'
String(3)
Required
expiredDate
Expiration date for Virtual Account. FORMAT: 'yyyy-MM-dd'T'HH:mm:ssTZD'
String(25)
Required
